### ISSUE TITLE
Weight mismatch error

### ISSUE THREAD

**Issue by eliflali** [QitaoZhao/PoseFormerV2#43]
Traceback (most recent call last):
  File "/content/PoseFormerV2/demo/vis.py", line 286, in <module>
    get_pose2D(video_path, output_dir)
  File "/content/PoseFormerV2/demo/vis.py", line 90, in get_pose2D
    keypoints, scores = hrnet_pose(video_path, det_dim=416, num_peroson=1, gen_output=True)
  File "/content/PoseFormerV2/demo/lib/hrnet/gen_kpts.py", line 95, in gen_video_kpts
    human_model = yolo_model(inp_dim=det_dim)
  File "/content/PoseFormerV2/demo/lib/yolov3/human_detector.py", line 88, in load_model
    model.load_weights(args.weight_file)
  File "/content/PoseFormerV2/demo/lib/yolov3/darknet.py", line 432, in load_weights
    conv_weights = conv_weights.view_as(conv.weight.data)
RuntimeError: shape '[256, 128, 3, 3]' is invalid for input of size 108955

**Comment by QitaoZhao** [comment]
By default, we use the `27_243_45.2.bin` model variant and hard-coded (sorry about that) model parameters. Could you check if you downloaded the correct checkpoint?

**Comment by QitaoZhao** [comment]
Closing due to inactivity. Please reopen if needed.
