### ISSUE TITLE
Question about 'bboxs_pre'

### ISSUE THREAD

**Issue by JackyXiao1515** [QitaoZhao/PoseFormerV2#45]
Hi, I got this problem when I testing a video, it works for other video but only one perticular has this error:

> Generating 2D pose...
>   0%|                                                                                                     | 0/1756 [00:00<?, ?it/s]No person detected!
>   0%|                                                                                                     | 0/1756 [00:01<?, ?it/s]
**> Traceback (most recent call last):
>   File "E:\PoseFormer\PoseFormerV2-main\demo\vis.py", line 287, in <module>
>     get_pose2D(video_path, output_dir)
>   File "E:\PoseFormer\PoseFormerV2-main\demo\vis.py", line 90, in get_pose2D
>     keypoints, scores = hrnet_pose(video_path, det_dim=416, num_peroson=1, gen_output=True)
>   File "E:\PoseFormer\PoseFormerV2-main\demo\lib\hrnet\gen_kpts.py", line 113, in gen_video_kpts
>     bboxs = bboxs_pre
> UnboundLocalError: local variable 'bboxs_pre' referenced before assignment**

It looks strange of 'no person detected' but I can still get output for other videos.

By the way, how can I generate 3D coordinates for joints? 

Thanks for answering!

**Comment by QitaoZhao** [comment]
I guess you can try the provided sample video [`https://github.com/QitaoZhao/PoseFormerV2/blob/main/demo/video/sample_video.mp4`](https://github.com/QitaoZhao/PoseFormerV2/blob/main/demo/video/sample_video.mp4) where 3D joints can be easily obtained after model forward pass.

**Comment by JackyXiao1515** [comment]
Thank you for your kindly answer! I've got the 3D coordinates. 

May I know how could I use PoseformerV2 to do a real-time pose detection? Cause PoseformerV2 works with videos, and I was wondering if it can still work with stream from cameras.

Best regards.

**Comment by QitaoZhao** [comment]
I'm not really sure, but I think a hack you can do is to repeat the current 2D pose as pseudo future frames. Therefore, you can run our model on these video sequences.

**Comment by QitaoZhao** [comment]
Closing due to inactivity. Please reopen if needed.
